### ISSUE TITLE
Rework perfil

### ISSUE THREAD

**Issue by alecsolace** [CatCodeSV/Place4All-Frontend#25]

**Comment by CyberLaidy** [comment]
Nuevo diseño del perfil de usuario, se han implementado nuevos botones para hacer más intuitivo el panel de control. 
Faltará confirmar si queremos que se desplieguen en dialogs o en otros componentes.
[https://www.figma.com/file/rzQx18ooKV53uDuuvtZOKO/Place4All?type=design&node-id=0-1&t=yvg5sAM8EtcQcpKz-0](url)

**Comment by CyberLaidy** [comment]
Subidos cambios de nuevo perfil de usuario y administrador, faltará perfil de restaurantes

**Comment by CyberLaidy** [comment]
- Faltará probar que llegan correctamente los datos en las diferentes pantallas, en concreto la de perfil/usuario donde encontraremos el nombre, apellido y avatar del usuario (nos llevará al iniciar sesión) y en la de perfil/privacidad donde encontraremos el resto de datos personales (tendremos que desplazarnos con los botones del perfil). 

- Verificar que todo funciona bien, y que el botón de cerrar sesión, desconecta al usuario correctamente.

**Comment by CyberLaidy** [comment]
Subido corrección de errores, cambios de interfaz web y responsive. 
.
Pendiente correcciones de Joaquin/Silvia
[Envío email para feedback de perfil de usuario (control de espacios)]
